[default_session]
startup_command = "git rev-parse --is-inside-work-tree &> /dev/null && lazygit"
preview_command = "eza --all --git --icons --color=always {}"
windows = [ "nvim" ]
[[window]]
name = "nvim"
startup_command = "nvim"

[[session]]
name="EKS DEV"
startup_command="k9s --context arn:aws:eks:us-east-1:597088057029:cluster/us-east-1-dev-cluster -n neuriphy"

[[session]]
name="EKS DEMO"
startup_command="k9s --context arn:aws:eks:us-east-1:597088057029:cluster/us-east-1-dev-cluster -n demo"

[[session]]
name="EKS PROD"
startup_command="k9s --context arn:aws:eks:us-east-1:597088057029:cluster/us-east-1-prod-cluster -n app"

